"""Assemble the static GitHub Pages build into ``docs/``.

GitHub Pages serves static files only, so the pure-Python engine runs in
the browser via Pyodide. This script bundles:

* the frontend (index.html / css / js / i18n / tile art), with asset
  paths rewritten from absolute ``/static`` to relative ``./`` so the
  site works under ``https://<user>.github.io/<repo>/``;
* the ``app.mahjong`` engine package + ``app.web_bridge`` as plain
  source the browser fetches into Pyodide's filesystem;
* ``config.js`` (turns on static mode) and ``pyodide-boot.js`` (loads
  Pyodide, mounts the engine, exposes ``window.MJEngine``).

Run from the repo root::

    python scripts/build_pages.py

It is idempotent — ``docs/`` is wiped and regenerated each time.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend" / "static"
DOCS = ROOT / "docs"
ENGINE_OUT = DOCS / "engine"

PYODIDE_VERSION = "0.26.4"

CONFIG_JS = """// Generated by scripts/build_pages.py — do not edit by hand.
// Presence of this file (loaded before app.js) switches the UI into
// static mode: no backend, the engine runs in-browser via Pyodide.
window.MJ_CONFIG = { static: true, tileBase: "./tiles" };
"""

PYODIDE_BOOT_JS = f"""// Generated by scripts/build_pages.py — do not edit by hand.
// Boots Pyodide, mounts the pure-Python engine, and exposes a tiny
// synchronous JSON API on window.MJEngine that app.js's Engine seam
// calls in static mode. window.MJEngineReady resolves when it is usable.
(function () {{
  const PYODIDE_BASE =
    "https://cdn.jsdelivr.net/pyodide/v{PYODIDE_VERSION}/full/";

  function overlay(show, msg) {{
    let el = document.getElementById("mj-boot-overlay");
    if (show) {{
      if (!el) {{
        el = document.createElement("div");
        el.id = "mj-boot-overlay";
        el.style.cssText =
          "position:fixed;inset:0;z-index:9999;display:flex;align-items:" +
          "center;justify-content:center;background:rgba(15,17,21,.92);" +
          "color:#e8e8e8;font:600 16px/1.5 system-ui,sans-serif;" +
          "text-align:center;padding:24px";
        document.body.appendChild(el);
      }}
      el.innerHTML =
        '<div><div style="font-size:22px;margin-bottom:10px">' +
        '🀄 MahjongAiScreen</div><div>' + msg + "</div>" +
        '<div style="opacity:.6;font-weight:400;margin-top:8px">' +
        "First load downloads the Python runtime (~6 MB, then cached)." +
        "</div></div>";
    }} else if (el) {{
      el.remove();
    }}
  }}

  function loadScript(src) {{
    return new Promise((res, rej) => {{
      const s = document.createElement("script");
      s.src = src;
      s.onload = res;
      s.onerror = () => rej(new Error("failed to load " + src));
      document.head.appendChild(s);
    }});
  }}

  window.MJEngineReady = (async function () {{
    try {{
      overlay(true, "Loading AI engine…");
      await loadScript(PYODIDE_BASE + "pyodide.js");
      const pyodide = await loadPyodide({{ indexURL: PYODIDE_BASE }});

      const manifest = await (await fetch("./engine/manifest.json")).json();
      pyodide.FS.mkdir("/engine");
      const seen = new Set(["/engine"]);
      for (const rel of manifest) {{
        const parts = rel.split("/");
        let dir = "/engine";
        for (let i = 0; i < parts.length - 1; i++) {{
          dir += "/" + parts[i];
          if (!seen.has(dir)) {{ pyodide.FS.mkdir(dir); seen.add(dir); }}
        }}
        const txt = await (await fetch("./engine/" + rel)).text();
        pyodide.FS.writeFile("/engine/" + rel, txt);
      }}

      pyodide.runPython("import sys; sys.path.insert(0, '/engine')");
      const br = pyodide.pyimport("app.web_bridge");
      window.MJEngine = {{
        tiles_json: () => br.tiles_json(),
        analyze_json: (s) => br.analyze_json(s),
        analyze_game_json: (s) => br.analyze_game_json(s),
        analyze_call_json: (s) => br.analyze_call_json(s),
      }};
      overlay(false);
      return true;
    }} catch (e) {{
      overlay(true, "Failed to load the engine: " + (e && e.message) +
        "<br>Please refresh.");
      throw e;
    }}
  }})();
}})();
"""


def _clean_docs() -> None:
    if DOCS.exists():
        shutil.rmtree(DOCS)
    DOCS.mkdir(parents=True)


def _copy_frontend() -> None:
    for name in ("styles.css", "app.js", "i18n.js"):
        shutil.copy2(FRONTEND / name, DOCS / name)
    shutil.copytree(FRONTEND / "tiles", DOCS / "tiles")

    html = (FRONTEND / "index.html").read_text(encoding="utf-8")
    html = (
        html.replace('href="/static/styles.css"', 'href="./styles.css"')
        .replace('src="/static/i18n.js"', 'src="./i18n.js"')
        .replace('src="/static/app.js"', 'src="./app.js"')
    )
    # config.js + pyodide-boot.js must run before app.js. Inject them just
    # before the i18n.js tag (which precedes app.js).
    inject = (
        '  <script src="./config.js"></script>\n'
        '  <script src="./pyodide-boot.js"></script>\n'
    )
    html = html.replace('  <script src="./i18n.js"></script>',
                         inject + '  <script src="./i18n.js"></script>')
    (DOCS / "index.html").write_text(html, encoding="utf-8")


def _copy_engine() -> list[str]:
    manifest: list[str] = []

    def emit(src: Path, rel: str) -> None:
        dst = ENGINE_OUT / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        manifest.append(rel)

    emit(ROOT / "backend" / "app" / "__init__.py", "app/__init__.py")
    emit(ROOT / "backend" / "app" / "web_bridge.py", "app/web_bridge.py")
    for py in sorted((ROOT / "backend" / "app" / "mahjong").glob("*.py")):
        emit(py, f"app/mahjong/{py.name}")

    (ENGINE_OUT / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    return manifest


def main() -> None:
    _clean_docs()
    _copy_frontend()
    files = _copy_engine()
    (DOCS / "config.js").write_text(CONFIG_JS, encoding="utf-8")
    (DOCS / "pyodide-boot.js").write_text(PYODIDE_BOOT_JS, encoding="utf-8")
    # .nojekyll: stop GitHub Pages' Jekyll from ignoring the engine dir.
    (DOCS / ".nojekyll").write_text("", encoding="utf-8")
    print(f"Built docs/ — {len(files)} engine files + frontend.")
    print("GitHub Pages: Settings → Pages → Deploy from branch → "
          "main / docs")


if __name__ == "__main__":
    main()
